# Form implementation generated from reading ui file '.\edit_settings_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 147)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.txtCsvDelimeter = QtWidgets.QLineEdit(parent=Dialog)
        self.txtCsvDelimeter.setObjectName("txtCsvDelimeter")
        self.gridLayout.addWidget(self.txtCsvDelimeter, 1, 0, 1, 3)
        self.btnAdd = QtWidgets.QPushButton(parent=Dialog)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(46, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.btnCancel = QtWidgets.QPushButton(parent=Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.gridLayout.addWidget(self.btnCancel, 4, 0, 1, 1)
        self.txtCsvAccuracy = QtWidgets.QLineEdit(parent=Dialog)
        self.txtCsvAccuracy.setObjectName("txtCsvAccuracy")
        self.gridLayout.addWidget(self.txtCsvAccuracy, 3, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Разделитель в csv файле"))
        self.label.setText(_translate("Dialog", "Количество цифр после запятой в csv файле"))
        self.btnAdd.setText(_translate("Dialog", "Изменить"))
        self.btnCancel.setText(_translate("Dialog", "Отмена"))
