# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 676)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setMinimumSize(QtCore.QSize(400, 0))
        self.tableView.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.plotFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.plotFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.plotFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.plotFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.plotFrame.setObjectName("plotFrame")
        self.horizontalLayout.addWidget(self.plotFrame)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1110, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(parent=self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.menuActionOpen_h5 = QtGui.QAction(parent=MainWindow)
        self.menuActionOpen_h5.setObjectName("menuActionOpen_h5")
        self.menuActionSave_csv = QtGui.QAction(parent=MainWindow)
        self.menuActionSave_csv.setObjectName("menuActionSave_csv")
        self.menuActionSettings = QtGui.QAction(parent=MainWindow)
        self.menuActionSettings.setObjectName("menuActionSettings")
        self.menuActionEditSettings = QtGui.QAction(parent=MainWindow)
        self.menuActionEditSettings.setObjectName("menuActionEditSettings")
        self.menuFile.addAction(self.menuActionOpen_h5)
        self.menuFile.addAction(self.menuActionSave_csv)
        self.menuOptions.addAction(self.menuActionEditSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuActionOpen_h5.setText(_translate("MainWindow", "Open h5"))
        self.menuActionSave_csv.setText(_translate("MainWindow", "Save csv"))
        self.menuActionSettings.setText(_translate("MainWindow", "Settings"))
        self.menuActionEditSettings.setText(_translate("MainWindow", "Settings"))
